### PR TITLE
Update rubocop version

### PR DESCRIPTION
**Pull request by miketheman**
Use latest released version

I wasn't entirely certain if this was the right/best way to update the hook's version, considering it's living inside an rbenv in a homedir, but I guessed this might be correct.

Happy to change it if this is the wrong direction.

### CODE REVIEW

**Comment by quentindemetz** [comment]
This repository was automatically generated by https://github.com/pre-commit/pre-commit-mirror-maker. I don't think it really makes sense to submit a pull request with a "manual" commit. I've run the script again to generate the last couple of versions.

If you need me to update this again, just submit an issue and I'll get around to it!

**Comment by miketheman** [comment]
@quentindemetz Thanks! I didn't know that's how these are made. Is there a way you can conceive of to have the update run automatically on release of the rubocop gem? I think I recall gemnasium offering some sort of "trigger a build when a new version of dependency is released".

**Comment by quentindemetz** [comment]
Not that I can think of, so far I've been running this on my laptop once in a while, I don't really see where the script would run ? I could set up a cron on an ec2 free tier instance, but so far I'm happy to bump it manually when needed.

**Comment by miketheman** [comment]
I found what I was recalling: http://blog.gemnasium.com/post/91568285935/let-gemnasium-auto-update-your-dependencies
As well as http://guides.rubygems.org/rubygems-org-api/#webhook-methods

The former link does not apply at all, mis-remembering. The latter likely requires more effort than I expected, so feel free to ignore.

Thanks for updating, and continuing to entertain this discussion! :smile:

**Pull request closed without merging**
