### PR TITLE
Create a README

### PR DESCRIPTION
**Pull request by matthieu-gendreau**

### CODE REVIEW

**Comment by tdeo** [comment]
Mirrors for pre-commit hooks have become obsolete with the introduction of support for local hooks in different languages. See [documentation](http://pre-commit.com/#repository-local-hooks) and [implementation](https://github.com/pre-commit/pre-commit/pull/489)

**Comment by matthieu-gendreau** [comment]
Local hooks are very nice but still not the standard as described in the [pre-commit website](http://pre-commit.com/#plugins).

Anyway if you really think that this repo shouldn't be used, the best would be to remove it from the [official hooks documentation of supported hooks](http://pre-commit.com/hooks.html) to avoid confusion?

On a side note I still find remote hooks can sometime be more convenient as they don't have to be pre installed.

**Comment by JonLev** [comment]
@matthieugendreau this could help you:
https://github.com/pre-commit/pre-commit-mirror-maker

**Comment by tdeo** [comment]
Or you can use local hook to avoid dependencies on external repos, see for instance https://github.com/bobar/tdfb/blob/master/.pre-commit-config.yaml#L18

**Comment by matthieu-gendreau** [comment]
Perfect thank you @JonLev and @tdeo !

**Comment by JrmKrb** [comment]
Thanks! I was using this remote hook for 3 years but it seems way cleaner as a local hook.

**Pull request closed without merging**
